# -*- coding: utf-8 -*-
"""my port scanner.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8arzhR2755pVt2oLoYP0KJvar5-t9sG
"""

import threading
import socket
from time import time, sleep

target = 'go.com'

def portscan(port):

    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(0.5)

    try:
        con = s.connect ((target,port))
        print('Port',port,"is open")
        con.close()

    except: 
        pass
r = 1 
for x in range(1,600): 
    t = threading.Thread(target=portscan,kwargs={'port':r}) 
    r += 1     
    t.start()

